// Generated by CoffeeScript 1.9.1
(function() {
  window.Mth = (function() {
    function Mth() {}

    Mth.clamp = function(x0, x1, x) {
      if (x < x0) {
        return x0;
      }
      if (x > x1) {
        return x1;
      }
      return x;
    };

    Mth.mix = function(x, y, a) {
      return (1.0 - a) * x + a * y;
    };

    Mth.smoothstep = function(x0, x1, x) {
      x = this.clamp(0, 1, (x - x0) / (x1 - x0));
      return x * x * (3.0 - 2.0 * x);
    };

    Mth.interval = function(w, x) {
      return x % w;
    };

    Mth.win = function(x0, x1, x2, x3, x) {
      return this.smoothstep(x0, x1, x) - this.smoothstep(x2, x3, x);
    };

    Mth.symwin = function(x0, x1, width, x) {
      return this.win(x0, x1, x0 + width, width + x1, x);
    };

    Mth.stepwin = function(x0, step, width, x) {
      return this.symwin(x0, x0 + step, width, x);
    };

    Mth.edgewin = function(x0, width, x) {
      if (x >= x0 && x < x0 + width) {
        return 1;
      }
      return 0;
    };

    Mth.pulse = function(k, x) {
      var h;
      h = k * x;
      return h * Math.pow(Math.E, 1.0 - h);
    };

    Mth.qpulse = function(c, w, x) {
      x = Math.abs(x - c);
      if (x > w) {
        return 0.0;
      }
      x /= w;
      return 1.0 - x * x * (3.0 - 2.0 * x);
    };

    return Mth;

  })();

}).call(this);
